site_name: 2022-2 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2022-2-MeasureSoftGram-Doc

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: index.html
  - Equipe:
    - Agenda e Ferramentas: equipe/agenda-e-ferramentas.md
    - Conhecimento e Disponibilidade: equipe/conhecimento-e-disponibilidade.md
  - Plano e Monitoramento:
    - Estrutura Análitica do Projeto: plano-monitoramento/EAP.md
    - Termo de Abertura do Projeto: plano-monitoramento/tap.md
    - Custos do Projeto: plano-monitoramento/custo_projeto.md
    - Analise de Riscos: plano-monitoramento/analise_riscos.md
  # - Visão de Produto:
  #   -
  - Contribuição:
    - Como contribuir?: politicas/contribuindo.md
    - Política de Branches: politicas/branches.md
    - Política de Commits: politicas/commits.md
    - Código de conduta: politicas/CODE_OF_CONDUCT.md
