site_name: 2022-2 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2022-2-MeasureSoftGram-Doc

theme:
  name: material
  features: navigation.tabs
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    primary: blue grey

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Manuais de Uso:
    - CLI: manual-de-uso/cli.md
  - Equipe:
      - Agenda e Ferramentas: equipe/agenda-e-ferramentas.md
      - Conhecimento e Disponibilidade: equipe/conhecimento-e-disponibilidade.md
  - Plano e Monitoramento:
    - Estrutura Análitica do Projeto: plano-monitoramento/EAP.md
    - Termo de Abertura do Projeto: plano-monitoramento/tap.md
    - Custos do Projeto: plano-monitoramento/custo_projeto.md
    - Analise de Riscos: plano-monitoramento/analise_riscos.md
    - Plano de Qualidade do Produto: plano-monitoramento/plano_de_qualidade.md
    - Arquitetura do Projeto: plano-monitoramento/documento_de_arquitetura.md
  - Visão de Produto:
    - Lean Inception: visao-produto/lean_inception.md
    - Backlog do Produto: visao-produto/product_backlog.md
  - Contribuição:
      - Como contribuir?: politicas/contribuindo.md
      - Política de Branches: politicas/branches.md
      - Política de Commits: politicas/commits.md
      - Código de conduta: politicas/CODE_OF_CONDUCT.md
  - Dojos:
    - Frontend: dojo/next_frontend.md
