site_name: 2022-2 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2022-2-MeasureSoftGram-Doc

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: index.html
  - Equipe:
    - Agenda e Ferramentas: equipe/agenda-e-ferramentas.md
  - Contribuição: 
    - Como contribuir?: policies/contributing.md
  # - Visão de Produto:
  #   - 
  # - Plano e Monitoramento:
  #   - 
