site_name: 2022-2 MeasureSoftGram
repo_url: https://github.com/fga-eps-mds/2022-2-MeasureSoftGram-Doc

theme:
  name: material
  features: navigation.tabs

nav:
  - Home: index.md
  - Equipe:
      - Agenda e Ferramentas: equipe/agenda-e-ferramentas.md
      - Conhecimento e Disponibilidade: equipe/conhecimento-e-disponibilidade.md
  - Plano e Monitoramento:
    - Estrutura Análitica do Projeto: plano-monitoramento/EAP.md
    - Termo de Abertura do Projeto: plano-monitoramento/tap.md
    - Custos do Projeto: plano-monitoramento/custo_projeto.md
    - Analise de Riscos: plano-monitoramento/analise_riscos.md
    - Plano de Qualidade do Produto: plano-monitoramento/plano_de_qualidade.md
    - Arquitetura do Projeto: plano-monitoramento/documento_de_arquitetura.md
    - Backlog do Produto: plano-monitoramento/product_backlog.md
  # - Visão de Produto:
  #   -
  - Contribuição:
      - Como contribuir?: politicas/contribuindo.md
      - Política de Branches: politicas/branches.md
      - Política de Commits: politicas/commits.md
      - Código de conduta: politicas/CODE_OF_CONDUCT.md
  - Dojos:
    - Frontend: dojo/next_frontend.md
